### ISSUE TITLE
Regression since 3.2

### ISSUE THREAD

**Issue by matbech** [hanickadot/compile-time-regular-expressions#131]
There is a regression somewhere (I haven't had the time yet to debug this) since v3.2 where some of the expressions I'm using are no longer matching. 
Working commit: https://github.com/hanickadot/compile-time-regular-expressions/commit/46a345e7faba8497f585ce5d180b5cb4f6a00544

**Comment by hanickadot** [comment]
Please provide a test case.

**Comment by matbech** [comment]
```
constexpr auto Pattern1 = ctll::fixed_string{ LR"(^([\-dlsDLS][\-rwxstlRWXSTL]{9}[+]?)\s*(\d+)?\s+(\S+)?\s+(.*?)?\s+(\d+|\d+\.\d+\S)\s+([A-Za-z][a-z][a-z])\s+(\d{1,2})\s+((\d{4,4})|(\d{1,2})[:\.](\d{2,2}))\s)" };

const wchar_t begin[]{L"drwxr-xr-x    2 1544     1544         4096 Mar 12  2013 .ftpcontrol"};
const auto end = begin + std::wcslen(begin);
const auto results = ctre::re<Pattern1>().search(begin, end);
static_assert(results.count() == 12, "unexpected count");
if (results)
{
// match
}
```

**Comment by hanickadot** [comment]
Thank you! Will look at it this evening.

**Comment by hanickadot** [comment]
Ok I was able to minimize it:
`static_assert(ctre::match<"(.*?)?x">("1x"));` and it happen in commit `73d55a5af55e9ff0ad70c20bc2aaffbeeae0a447`

trying to find the problem...

**Comment by hanickadot** [comment]
Technically the problem was with lazy star cycle inside a greedy optional. Changing it into possessive star would be better. It worked with original optional implementation, but recently I came with change that `optional<...>` is just alias to `repeat<0,1,...>` which unearthed the problem of the regex.

**Comment by hanickadot** [comment]
Fixed in v3.3

**Comment by matbech** [comment]
Thank you :-)

**Comment by matbech** [comment]
I'm curious why this issue has been closed as this is still broken with the latest commit.

**Comment by hanickadot** [comment]
It's bit deeper problem, fix is WIP in branch `fix-for-cycles` but it introduces different problems, mostly performance and in also it can result in an excessive stack usage. I merged latest change from main into the branch, but I'm not ready to merge it into main yet.
